#! /bin/sh

sxhkd &

bspc monitor eDP1 -d I II III
bspc monitor HDMI1 -d I II III

bspc config border_width        2
bspc config window_gap          2
bspc config padding             0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer _modifier     mod4
bspc config pointer _action1      move
bspc config pointer _action2      resize_side
bspc config pointer _action3      resize_corner

feh --bg-scale ~/Pictures/wallpapers/wallpaper_roses.jpg
