#! /bin/sh

feh --bg-scale ~/Pictures/wallpapers/macos-12-dark.jpg

for m in $(bspc query -M); do bspc monitor $m -d α β γ;done

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc config window_gap          15
bspc config bottom_padding      0
bspc config top_padding         0
bspc config border_width        2

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer _modifier     mod4
bspc config pointer _action1      move

color=#1d2021
color_focused=#ea6962
color_active=#32302f

bspc config normal_border_color   "${color}"
bspc config focused_border_color  "${color_focused}"
bspc config active_border_color   "${color_active}"

bspc rule -a Chromium desktop='^2'
